name: Generate Archive

on:
  workflow_dispatch:

permissions:
  contents: write


jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Generate Archive
        run: npm run generate

      - name: Upload Archive
        uses: actions/upload-artifact@v2
        with:
          name: archive.db